server {
  listen 443 ssl;
  listen [::]:443 ssl;
  http2 on;

  access_log /dev/stdout;
  error_log /dev/stderr info;

  server_name kaahmed.42.fr;

  ssl_certificate     /etc/nginx/ssl/kaahmed.crt;
  ssl_certificate_key /etc/nginx/ssl/kaahmed.key;
  ssl_protocols TLSv1.2 TLSv1.3;
  ssl_ciphers HIGH:!aNULL:!MD5;

  root /var/www/html;
  index index.php index.html;

  location / {
    try_files $uri $uri/ /index.php?$args;
  }

  location ~ \.php$ {
    # Send to wordpress container php-fpm
    fastcgi_pass  wordpress:9000;

    include       fastcgi_params;
    # This must be set — tells php-fpm which file to execute
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    fastcgi_index index.php;
  }
}